<?php
/**
 * Created by PhpStorm.
 * User: billy
 * Date: 10/02/2017
 * Time: 5:20 PM
 */

namespace App\Modules\Enums;

class ErrorCode
{
    const DATABASE_ERROR = "DATABASE_ERROR";
    const PARAM_ERROR = "PARAM_ERROR";
    const FATAL_ERROR = "FATAL_ERROR";
    const SERVER_ERROR = "SERVER_ERROR";

    const RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";

    //user_related
    const TOKEN_NOT_PROVIDED = "TOKEN_NOT_PROVIDED";
    const TOKEN_EXPIRE = "TOKEN_EXPIRE";
    const TOKEN_INVALID = "TOKEN_INVALID";
    const USER_NOT_EXIST = "USER_NOT_EXIST";
    const USER_ALREADY_EXIST = "USER_ALREADY_EXIST";
    const LOGIN_FAILED = "LOGIN_FAILED";
    const CREATE_TOKEN_FAILED = "CREATE_TOKEN_FAILED";
    const INPUT_INCOMPLETE = "INPUT_INCOMPLETE";
    const RESTAURANT_BLOCKED = "RESTAURANT_BLOCKED";

    //dinning time related
    const DINNING_TIME_CONFLICT = "DINNING_TIME_CONFLICT";
    const NOT_IN_DINNING_TIME = "NOT_IN_DINNING_TIME";
    const DINNING_TIME_NOT_EXIST = "DINNING_TIME_NOT_EXIST";

    //consume rule conflict
    const CONSUME_RULE_CONFLICT = "CONSUME_RULE_CONFLICT";

    //card related
    const CARD_NOT_EXIST = "CARD_NOT_EXIST";
    const CARD_STATUS_INCORRECT = "CARD_STATUS_INCORRECT";
    const INVALID_CARD = "INVALID_CARD";

    //customer related
    const BALANCE_NOT_ENOUGH = 'BALANCE_NOT_ENOUGH';

    //label related
    const LABEL_NOT_EXIST = "LABEL_NOT_EXIST";
    const LABEL_CATEGORY_NOT_BINDED = "LABEL_CATEGORY_NOT_BINDED";
    const LABEL_CATEGORY_ALREADY_BINDED = "LABEL_CATEGORY_ALREADY_BINDED";
    const LABEL_CATEGORY_NOT_BIND_GOOD = "LABEL_CATEGORY_NOT_BIND_GOOD";
    const LABEL_CATEGORY_BIND_ON_OTHER_RESTAURANT = "LABEL_CATEGORY_BIND_ON_OTHER_RESTAURANT";

    //goods related
    const GOODS_NOT_EXIST = 'GOODS_NOT_EXIST';
    const NO_DEFAULT_SHOP = 'NO_DEFAULT_SHOP';
    const GOODS_DINNING_TIME_BIND_LABEL_CATEGORY_CONFLICT = "GOODS_DINNING_TIME_BIND_LABEL_CATEGORY_CONFLICT";

    //recharge order
    const RECHARGE_ORDER_CANCELED = 'RECHARGE_ORDER_CANCELED';

    //order related
    const ORDER_GOODS_NOT_EXIST = 'ORDER_GOODS_NOT_EXIST';
    const ORDER_STATUS_INCORRECT = 'ORDER_STATUS_INCORRECT';

    //pay method related
    const PAY_METHOD_NOT_PROVIDED = 'PAY_METHOD_NOT_PROVIDED';
    const PAY_METHOD_NOT_SUPPORTED = 'PAY_METHOD_NOT_SUPPORTED';
    const PAY_FAILED = 'PAY_FAILED';

    const DEPARTMENT_ALREADY_EXIST = "DEPARTMENT_ALREADY_EXIST";
    const SHOP_ALREADY_EXIST = "SHOP_ALREADY_EXIST";
    const CONSUME_CATEGORY_ALREADY_EXIST = "CONSUME_CATEGORY_ALREADY_EXIST";
    const LABEL_CATEGORY_ALREADY_EXIST = "LABEL_CATEGORY_ALREADY_EXIST";
    const CARD_ALREADY_EXIST = "CARD_ALREADY_EXIST";
    const DEVICE_ALREADY_EXIST = "DEVICE_ALREADY_EXIST";
}